---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  generateName: powervs-actuator-testing-machine-
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: powervs-actuator-k8s
spec:
  providerSpec:
    value:
      apiVersion: powervsproviderconfig.openshift.io/v1alpha1
      kind: PowerVSMachineProviderConfig
      serviceInstance:
        id: e449d86e-c3a0-4c07-959e-8557fdf55482
      image:
        name: rhcos-49-84-202108041519-0
      userDataSecret:
        name: worker-user-data
      credentialsSecret:
        name: powervs-credentials
      sysType: s922
      procType: shared
      processors: 0.25
      memory: 8
      network:
        name: pvs-ipi-net
      keyPairName: karthik-ssh
